language: php
php:
  - 7.0
  - 5.6
  #- 5.4

git:
  depth: 5

install:
  - composer self-update --preview
  - composer install

script:
  - composer test

after_script:
  - composer --version
  - git --version

#End.
